spring:
  application:
    name: Zukbam-BE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: ${JPA_SHOW_SQL:false}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }
  secret: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP:3600}
  refresh-exp: ${JWT_REFRESH_EXP:1209600}

auth:
  email:
    verified-token-exp: ${AUTH_EMAIL_VERIFIED_TOKEN_EXP:1800}
